config/routes.rb
Forage::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :shallow => true do
    resources :listings
  end

  resources :categories
  resources :listings, :only => :index
  resources :users, :only => :index

  resources :pages

  
  get ':action' => 'pages#action'
  
  root 'application#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	belongs_to :category


	# def category_id=(the_id)
	# 	self.category_ids << the_id
	# end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :create]
  

  # GET /listings
  # GET /listings.json
  def index
      #if there's a user logged in and they hit 'my listings', filter by their listings....
      if @user.present? 
        @listings = @user.listings
      else
        @listings = Listing.all
      end
      all_listing_count = @listings.count
    

      #the user comes here if they use the search function...
      if params[:search_term].present?
        search_term = "%#{params[:search_term]}%"
        @listings = @listings.where("name ilike ?", search_term) 
        # if @listings == nil
        # render text: "" 
        # end
        search_count = @listings.count


      end

      if params[:suburb].present?
        search_term = "%#{params[:suburb]}%"
        @listings = @listings.where("location ilike ?", search_term)
      end
      final_count = @listings.count


      if final_count == 0

        flash.now.notice = "There aren't any listings that match '#{h params[:search_term]}' and '#{h params[:suburb]}'. <a href='/'>Try some different search terms</a> or check out <a href='/listings'>All Listings</a> instead. ".html_safe
      
        if search_count != 0 && params[:search_term].present?
          flash.now.notice = "There aren't any listings that match '#{h params[:search_term]}' and '#{h params[:suburb]}' specifically. There are <a href='/listings?utf8=✓&search_term=#{params[:search_term]}&suburb=&commit=Forage'>#{search_count} listings for just '#{h params[:search_term]}'</a> though! <a href='/'>Try some different search terms</a> or check out <a href='/listings'>All Listings</a> instead. ".html_safe
        end

      else 
        
      end

      # functions to sort by name or location....
      @sort = params[:sort] || :name
      @sort_by = params[:sort_by].try(:to_sym) || :asc
      @listings = @listings.order(@sort => @sort_by)

      #functions to filter by transaction type...

      if params[:filter].present?
      filter_type = "#{params[:filter]}"
      @listings = @listings.where("transaction_type = ?", filter_type)
      @listings_count = @listings.count 
        if @listings_count == 0
          flash.now.notice = "There currently aren\'t any listings to #{filter_type} right now. Try filtering by something else!"
        end
      end
  



  end
  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
  end

  # GET /listings/new
  def new
    @listing = current_user.listings.new
  end

  # GET /listings/1/edit
  def edit
    @categories = Category.all
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing for #{@listing.name} was successfully created." }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id]) if params[:user_id].present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :amount, :description, :location, :transaction_type, :cost, :expiry, :user_id, :pictures, :location_state, :sold, :sold_to, :category_id)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="form-group">
<%= form_for([@user, @listing]) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'What are you selling?' %><br>
    <%= f.text_field :name, placeholder: 'EG Carrot' %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :size => "30x12", placeholder: 'Describe something about what you\'re listing... where it came from, whether you used pestides, if its an heirloom variety etc... ' %>
  </div>
  <div class="field">
    <%= f.label :location, "Surburb and state where the buyer will pick up from..." %><br>
    <%= f.text_field :location %>

    <%= f.radio_button(:location_state, "NSW") %>
    <%= f.label(:location_state, "NSW") %>
    <%= f.radio_button(:location_state, "QLD") %>
    <%= f.label(:location_state, "QLD") %>
    <%= f.radio_button(:location_state, "NT") %>
    <%= f.label(:location_state, "NT") %>
    <%= f.radio_button(:location_state, "WA") %>
    <%= f.label(:location_state, "WA") %>
    <%= f.radio_button(:location_state, "SA") %>
    <%= f.label(:location_state, "SA") %>
    <%= f.radio_button(:location_state, "VIC") %>
    <%= f.label(:location_state, "VIC") %>
    <%= f.radio_button(:location_state, "ACT") %>
    <%= f.label(:location_state, "ACT") %>


  </div>
  <div class="field">
    <%= f.label :transaction_type %><br>

    <%= f.radio_button(:transaction_type, "grab") %>
    <%= f.label(:transaction_type, "Grab (Giving away for free)") %><br />

    <%= f.radio_button(:transaction_type, "swap") %>
    <%= f.label(:transaction_type, "Swap for something else (specify in your description)") %><br />

    <%= f.radio_button(:transaction_type, "buy") %>
    <%= f.label(:transaction_type, "Sell for cash") %>
    <%= f.label :cost, ' -- How much for? (Round to the nearest dollar)' %>
    <%= f.number_field :cost %>
</div>

  <div class="field">
    <%= f.label :expiry %><br>
    <%= f.datetime_select :expiry %>
  </div>
  <div class="field">
    <%= f.label :pictures, 'Add a picture of what you\'re offering!' %><br>
    <%= f.text_field :pictures %>
  </div>
  <div class="field">
    <% f.hidden_field :sold, :value => false %>
  </div>
  <div class="field">
    <% f.hidden_field :sold_to, :value => 'No one yet!' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-danger' %>
  </div>
<% end %>
</div>

app/views/listings/_resultsmenu.html.erb
    <% new_sort_by = (@sort_by == :asc) ? :desc : :asc

            #the long version of the above
            # new_sort_by = if sort_by == :asc
            #     :desc
            # else
            #     :asc
            # end

    %>


<nav class="navbar navbar-default" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#filter-navbar-collapse-1">
        <span class="sr-only">Toggle filters and sorting options</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="filter-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sort Results<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sort by Name #{new_sort_by}", listings_path(:sort => :name, :sort_by => new_sort_by) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sort by Location #{new_sort_by}", listings_path(:sort => :location, :sort_by => new_sort_by) %></li>
            <li class="divider"></li>
            <li>PUT THAT LINKTO HERE</li>
            <li class="divider"></li>

          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filter Results<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Filter by Grabs", listings_path(:filter => 'grab') %> </li>
            <li class="divider"></li>
            <li><%= link_to "Filter by Swaps", listings_path(:filter => 'swap') %></li>
            <li class="divider"></li>
            <li><%= link_to "Filter by things to buy", listings_path(:filter => 'buy') %></li>
            <li class="divider"></li>
            <li><%= link_to "Filter by Qwerties", listings_path(:filter => 'fdsjfdsjk') %></li>
            <li class="divider"></li>
          </ul>
        </li>
      </ul>

 
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/listings/edit.html.erb
<%= @title = 'Edit your listing'  %>

<%= render 'form' %>

<div class="btn-group btn-group-sm">
<%= link_to 'Show', listing_path(@listing), :class => 'btn btn-info' %>
<%= link_to 'Back', listings_path, :class => 'btn btn-default' %>
</div>

app/views/listings/index.html.erb
<%  @title = "All listings"

    if user_signed_in? && @user.present?

    @title = "#{@user.username}'s Listings"

    elsif (params[:search_term] || params[:suburb]).present?

        @title = "#{pluralize @listings.size, 'Result'} for your Search...."

    end


    %>


    <!-- render the filters menu, and make sure the notice for errors comes under this... -->
    <% content_for :filters do %>
    <%= render partial: 'listings/resultsmenu'%> 
    <% end%>

    <% @listings.each do |listing| %>
    <div class="listview">
        <div class="listimage">
        <%= link_to (image_tag listing.pictures), listing_path(listing) %>
        </div>
        <div class="listcontent">
        <h3><%= link_to (pluralize listing.amount, listing.name), listing_path(listing) %></h3>
        <em>Listed by <%= listing.user.username if listing.user.present? %> in <%= listing.location %>, <%= listing.location_state %></em>
        <br /><p><%= listing.transaction_type %></p>
        <p>Expires on <%= listing.expiry %></p>
            <div class="btn-group">

            <%= link_to 'View', listing_path(listing), :class => 'btn btn-default' %>
            <% if user_signed_in? && current_user == listing.user %>
                <%= link_to 'Edit', edit_listing_path(listing), :class => 'btn btn-success' %>
                <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'%>
            <% end %>
            </div>
        </div>
      
      </div>
    <% end %>


<br>


<%= link_to "Make a new listing", new_user_listing_path(@user), :class => 'btn btn-default' if @user.present? %>

app/views/listings/new.html.erb
<%= @title = 'Create a new listing' %>

<%= render 'form' %>

<%= link_to 'Back', listings_path, :class => 'btn btn-default' %>

app/views/listings/show.html.erb
<div class="listingbanner" style="background-image: url('<%= @listing.pictures %>');">
<div class="listingbanneroverlay">
<div class="listingheading">
<h1><%= @listing.name %></h1>
<h3>offered by <%= @listing.user.username %></h3>
</div>
</div>

</div>

<div class="listingcontent">
<h3>
  <%= @listing.amount %> <%= @listing.name%> located in <%= @listing.location %>, <%= @listing.location_state %>
</h3>


  <% if @listing.sold == true %>
  <h3>This item is sold.</h3>
  <% else %>
  <p>
  <strong>This listing is offered until:</strong>
  <%= @listing.expiry %>
  </p>
  <% end %>
</p>

  <p><strong><%= @listing.user.username %>'s <%= @listing.name %> is to <%= @listing.transaction_type %></strong></p>

<% if @listing.cost != nil %>
  <p><strong>Price offered:</strong><br />
  $<%= @listing.cost %></p>
<% end %>

<p><%= @listing.description %></p>

<p>
  <%= image_tag @listing.pictures, :width => '300' %>
</p>



<% if @listing.sold == true %>
<p>
  <strong>Sold to:</strong>
  <%= @listing.sold_to %>
</p>
<% elsif current_user != @listing.user || current_user == nil %>
<!-- not working yet, need to pass params -->
<!--   <%= button_to 'Reserve & Collect', controller: '/pages', action: :orderConfirm, :method => get, :params => (user_id, listing_id, @listing.name), :class => 'btn btn-success' %><br /><br /> -->

<% end %>



<div class="btn-group">
<%= link_to 'Edit', edit_listing_path(@listing), :class => 'btn btn-success' if user_signed_in? && current_user == @listing.user %>
<%= link_to 'Back', listings_path, :class => 'btn btn-default' %>
<%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' if user_signed_in? && current_user == @listing.user %>
</div>

</div>