config/routes.rb
Forage::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :shallow => true do
    resources :listings
  end

  resources :categories
  resources :listings, :only => :index
  resources :users, :only => :index

  resources :pages

  
  get ':action' => 'pages#action'
  
  root 'application#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ERB::Util 

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name << :username
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<ul>
	<li><%= link_to 'Home', root_path %></li>
	<li><%= link_to 'About Forage', controller: '/pages', action: :about %></li>
	<li><%= link_to 'Contact/ Feedback', "https://forage-for.uservoice.com", :target => 'blank' %></li>

</ul>


<!-- Google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47890886-1', 'forage-for.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/application/_logo.html.erb
	<div class="brandholder">
		
	<%= link_to (image_tag 'superlogo.png', :width => 150, :class => 'brand'), root_path %>

			<div class="brand">
			<h1 class="brandname">Forage</h1>
			<h2 class="brandsubtitle">Find fresh.</h2>
			</div>
		</div>

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container-fluid">

	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Members', users_path %></li>
				<li><%= link_to 'All Listings', listings_path %></li>
				<li><%= link_to 'Contact/ Feedback', "https://forage-for.uservoice.com", :target => 'blank' %></li>
			</ul>
		

			<%= render partial: 'application/userpanel' %>
		</div> <!-- navbar colapse -->
	</div> <!-- end container fluid div -->
</nav>

app/views/application/_userpanel.html.erb
	  <% if user_signed_in? %>


     <ul class="nav navbar-nav navbar-right">
 		<li><%= image_tag current_user.avatar, :width => 50, :class => 'loggedinavatar' %></li>
 		<li class="userpaneltext">Welcome, <strong><%= current_user.name %>!</strong><br /> <em><%= current_user.email %></em></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions &amp; Settings <b class="caret"></b></a>
          <ul class="dropdown-menu">
			  <li><%= link_to 'Account Settings', edit_user_registration_path, :class => 'navbar-link' %></li>
			  <li><%= link_to 'Profile Settings', edit_user_path(current_user.id) %></li>
			  <li><%= link_to 'View Profile', current_user %></li>
			  <li><%= link_to 'See my listings', user_listings_path(current_user.id) %></li>
			  <li><%= link_to "Make a new listing", new_user_listing_path(current_user.id) %></li>
			  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          </ul>
        </li>
      </ul>


      	<% else %>
	     <ul class="nav navbar-nav navbar-right">

				  <li><%= link_to "Sign up", new_user_registration_path, :class => 'btn'  %></li>
				  <li><%= link_to "Login", new_user_session_path, :class => 'btn'  %></li>
	      </ul>
        </li>
      </ul>
<% end %>


	
	  

app/views/application/index.html.erb
<div class="homesearch">

<%= form_tag listings_path, method: :get do %>
<h1>I'm looking for...
<%= text_field_tag :search_term, nil, :class => 'searchbar', placeholder: 'Carrots' %>
in 
<%= text_field_tag :suburb, nil, :class => 'searchbar', placeholder: 'Sydney' %><br /><br /></h1>
<%= submit_tag 'Forage', :class => 'btn btn-go' %>
<% end %>

</div>